# Generated by Django 4.2 on 2023-06-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_type_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='static/images')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groceries_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='static/images')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='H_K_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='static/images')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category_type',
            name='Catg_Name',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='Catg_Name',
        ),
        migrations.DeleteModel(
            name='Category_shop',
        ),
        migrations.DeleteModel(
            name='Category_type',
        ),
        migrations.DeleteModel(
            name='Product_shop',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
    ]
