# Generated by Django 4.2 on 2023-06-08 12:39

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cloth_product_groceries_product_h_k_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=20)),
                ('product_desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='static/images')),
                ('elec_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category_shop')),
            ],
        ),
    ]
