# Generated by Django 4.2 on 2023-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_shop_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
