# Generated by Django 4.1.4 on 2023-06-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_shop_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cloth_Product',
        ),
        migrations.DeleteModel(
            name='Elec_Product',
        ),
        migrations.DeleteModel(
            name='Groceries_Product',
        ),
        migrations.DeleteModel(
            name='H_K_Product',
        ),
    ]
