# Generated by Django 4.1.4 on 2023-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_cloth_product_delete_elec_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_image',
            field=models.FileField(default='', upload_to='static/images'),
        ),
    ]
