# Generated by Django 4.1.4 on 2023-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_shop_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
