# Generated by Django 4.1.4 on 2023-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_shop_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_image',
            field=models.FileField(default='', null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
