# Generated by Django 4.1.4 on 2023-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_shop_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_image',
            field=models.FileField(default='', null=True, upload_to='media/static/images'),
        ),
    ]
